name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
      - cicd
    # paths:
    #   - 'database/Dockerfile'
    #   - 'backend/Dockerfile'
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Ste up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build Maven
        run: mvn -f ./backend/pom.xml clean package
        working-directory: ./backend

      - name: Build image runtraildb and runtrailbe
        run: |
          docker build ./database/ -t 10102004tan/runtraildb:latest
          docker build ./backend/ -t 10102004tan/runtrailbe:latest
        
      - name: push image to docker hub
        run: |
          docker login -u 10102004tan -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push 10102004tan/runtraildb:latest
          docker push 10102004tan/runtrailbe:latest
