name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
      - cicd
    paths:
      - 'database/**'
      - 'backend/**'
      - '.github/workflows/buildDocker.yml'
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Maven
        run: mvn clean package -DskipTests
        working-directory: ./backend

      - name: Build image runtraildb and runtrailbe
        run: |
          docker build ./database/ -t 10102004tan/runtraildb:latest
          docker build ./backend/ -t 10102004tan/runtrailbe:latest
        
      - name: Push image to Docker hub
        run: |
          docker login -u 10102004tan -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push 10102004tan/runtraildb:latest
          docker push 10102004tan/runtrailbe:latest
